# Generated by Django 3.0.6 on 2021-06-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='count',
            field=models.IntegerField(),
        ),
    ]
