# Generated by Django 3.0.6 on 2021-06-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210618_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='headline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
